name: Test using the docker image
on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

permissions:
  contents: read
  packages: write

jobs:
  test-wine:
    runs-on: ubuntu-24.04-arm
    container: ghcr.io/mstorsjo/wine
    steps:
      - name: Test wine
        run: |
          set -x
          whoami
          id
          pwd
          echo $HOME
          echo $WINEPREFIX
          ls -la /
          ls -la /github
          ls -la /github/home
          wine wineboot
          curl -LO https://martin.st/temp/hello-aarch64.exe
          curl -LO https://martin.st/temp/hello-armv7.exe
          wine hello-aarch64.exe
          wine hello-armv7.exe

  test-wine-arm64:
    runs-on: ubuntu-24.04
    container: linaro/wine-arm64
    steps:
      - name: Test wine
        run: |
          set -x
          whoami
          id
          pwd
          echo $HOME
          echo $WINEPREFIX
          ls -la /
          ls -la /github
          ls -la /github/home
          wine-arm64 wineboot
          curl -LO https://martin.st/temp/hello-aarch64.exe
          wine-arm64 hello-aarch64.exe
