name: Build a docker image
on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build test images
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: ./Dockerfile
          tags: |
            ubuntu-wine:latest
      - name: Test running binaries
        run: |
          set -x
          cd /tmp
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz
          tar -Jxvf llvm-mingw-*.tar.xz
          rm -f llvm-mingw-*.tar.xz
          mv llvm-mingw-* llvm-mingw
          curl -LO https://raw.githubusercontent.com/mstorsjo/llvm-mingw/refs/tags/20260602/test/hello.c
          for arch in aarch64 armv7; do
              ./llvm-mingw/bin/$arch-w64-mingw32-clang hello.c -o hello-$arch.exe
              docker run -v .:/host ubuntu-wine wine /host/hello-$arch.exe
          done
      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:11.0-v1
